name: Build

on: push

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test
      BRIDGETOWN_ENV: production
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn

      - name: "Install dependencies with Yarn"
        run: yarn install

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build
        run: yarn deploy

      - name: Test
        run: yarn test
        if: success()

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: output
